//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libros
    {
        public int ID { get; set; }
        [Display(Name = "Libro")]
        public string Libros1 { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdComprador { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> StockMax { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
